#!/usr/bin/env node
/**
 * CMS Plan Benefit Package (PBP) Benefits to Benefit Plan Standard importer
 *
 * Reads the PBP Benefits files that CMS publishes for each contract year
 * (Medicare Advantage) and writes one Benefit Plan Standard v1.2.0 document for
 * one plan. It writes BPS JSON only. Spec: docs/specs/pbp-importer.md; file
 * layout: docs/specs/pbp-record-layout-notes.md.
 *
 * It writes the plan level (identity, plan type, service area, plan year,
 * deductibles, out-of-pocket maximums, network tiers) and the benefits named in
 * fhir/pbp-crosswalk.json (the workgroup MVP), with cost shares per network
 * tier, ranges, day intervals, limits and coverage.
 *
 * The files are not in the repository. Put them in data/pbp/<year>/ (git-ignored),
 * unzipped, with a download.json that records the download date. The golden
 * plans' rows are committed in test/fixtures/pbp/<year>/ for the test.
 *
 * buildDocument() is a pure function: no network, no clock, no randomness.
 *
 * Usage:
 *   node scripts/from-pbp.js --year 2027 --plan H2406-013-000 [--out <file>]
 *   node scripts/from-pbp.js --year 2027 --contract H2406        list the contract's plans
 *   node scripts/from-pbp.js --write-golden                       regenerate examples/*.pbp.json (needs data/pbp/)
 *   node scripts/from-pbp.js --write-fixtures                     re-cut test/fixtures/pbp/ (needs data/pbp/)
 *   options: --data <dir> (default data/pbp), --downloaded <YYYY-MM-DD> (default from download.json)
 *
 * Exit codes: 0 = written or listed, 1 = error (nothing is written).
 */

'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(REPO_ROOT, 'data', 'pbp');
const EXAMPLES_DIR = path.join(REPO_ROOT, 'examples');
// Rows of the golden plans cut from every file the importer reads (committed;
// data/ is git-ignored, so they cannot live there). Spec section 13.
const FIXTURE_DIR = path.join(REPO_ROOT, 'test', 'fixtures', 'pbp');

// The golden plans: examples/<slug>.pbp.json, regenerated by --write-golden from
// the full files, their rows cut into FIXTURE_DIR by --write-fixtures, and
// checked by scripts/from-pbp.test.js. Spec section 13.
const GOLDEN = [
  { year: 2027, plan: 'H2406-013-000', why: 'Local PPO; the Summary of Benefits check plan; decision 1 out-of-network deductible' },
  { year: 2027, plan: 'H1036-068-000', why: 'HMO; no deductible; copay ranges' },
  { year: 2027, plan: 'H1609-028-000', why: 'HMO-POS; point-of-service groups; decision 4 POS deductible' },
  { year: 2027, plan: 'H5533-019-000', why: 'Local PPO with inpatient hospital cost tiers (IN_1A_TIER_1, IN_1A_TIER_2)' },
  { year: 2027, plan: 'H5425-140-000', why: 'HMO; hearing aids covered under the 18a maximum (shared_limit_id); decision S1 $0 steps' },
];
const SCHEMA_VERSION = '1.2.0';
const PBP_ZIP = (year) => `https://www.cms.gov/files/zip/pbp-benefits-${year}.zip`;

// ---- tab-delimited text, Windows-1252, streamed ----------------------------------------
// Records end at CRLF. No quoting. A record whose field count differs from the
// header, or a stray CR or LF inside a record, is an error. Header names are
// lowercased; a name that appears twice must hold the same value in both places.
const DECODER = new TextDecoder('windows-1252');

async function streamTsv(file, onRow) {
  const name = path.basename(file);
  let header = null;
  let firstIndex = null;
  let dupPairs = [];
  let carry = '';
  let line = 0;
  const handle = (rec) => {
    line++;
    if (/[\r\n]/.test(rec)) throw new Error(`${name}: record ${line} holds a line break that is not CRLF`);
    const f = rec.split('\t');
    if (!header) {
      header = f.map((h) => h.trim().toLowerCase());
      firstIndex = new Map();
      header.forEach((h, i) => {
        if (firstIndex.has(h)) dupPairs.push([firstIndex.get(h), i, h]);
        else firstIndex.set(h, i);
      });
      return;
    }
    if (f.length !== header.length) throw new Error(`${name}: record ${line} has ${f.length} fields, the header has ${header.length}`);
    for (const [a, b, h] of dupPairs) {
      if (f[a] !== f[b]) throw new Error(`${name}: record ${line}: the 2 "${h}" columns disagree ("${f[a]}", "${f[b]}")`);
    }
    onRow(f, firstIndex);
  };
  const stream = fs.createReadStream(file, { highWaterMark: 1 << 20 });
  for await (const chunk of stream) {
    // Windows-1252 is 1 byte per character, so each chunk decodes on its own.
    const text = carry + DECODER.decode(chunk);
    const parts = text.split('\r\n');
    carry = parts.pop();
    for (const p of parts) handle(p);
  }
  if (carry !== '') handle(carry);
  if (!header) throw new Error(`${name}: empty file`);
}

// The rows of one file whose first 3 columns are the plan key, as objects keyed
// by lowercased column name. The file's segment is unpadded ("0"), so it is
// compared as a number.
async function rowsFor(file, key) {
  const out = [];
  await streamTsv(file, (f, idx) => {
    if (f[0] !== key.contract || f[1] !== key.plan) return;
    if (!/^\d{1,3}$/.test(f[2])) throw new Error(`${path.basename(file)}: segment_id "${f[2]}" is not 1 to 3 digits`);
    if (Number(f[2]) !== Number(key.segment)) return;
    const row = {};
    for (const [h, i] of idx) row[h] = f[i];
    out.push(row);
  });
  return out;
}

// ---- code lists, verbatim from PBP_Benefits_2027_dictionary.xlsx ------------------------
const PLAN_TYPE_LABELS = {
  '01': 'HMO', '02': 'HMOPOS', '04': 'Local PPO', '05': 'PSO (State License)', '07': 'MSA', '08': 'RFB PFFS',
  '09': 'PFFS', '18': '1876 Cost', '19': 'HCPP - 1833 Cost', '20': 'National Pace', '29': 'Medicare Prescription Drug Plan',
  '30': 'Employer/Union Only Direct Contract PDP', '31': 'Regional PPO', '32': 'Fallback',
  '40': 'Employer/Union Only Direct Contract PFFS', '42': 'RFB HMO', '43': 'RFB HMOPOS', '44': 'RFB Local PPO',
  '45': 'RFB PSO (State License)', '47': 'Employer Direct PPO',
};
// MVP plan types (spec section 1) and the BPS plan_type each one is written as
// (HMO_POS added to vocabularies/plan-types.json for this importer, spec 4.1).
const MVP_PLAN_TYPES = { '01': 'HMO', '02': 'HMO_POS', '04': 'PPO', '31': 'PPO' };
const PPO_TYPES = new Set(['04', '31']);
const DED_TYPES = {
  1: 'Medicare-Defined Part A Deductible amount',
  2: 'Medicare-Defined Part B Deductible amount',
  3: 'Medicare-Defined Part A and B Deductible amount combined as a single deductible',
  4: 'Other, Indicate amount',
};
const MOOP_TYPES = { 1: 'Lower', 2: 'Mandatory', 3: 'Intermediate' };
const HOSPITAL_TIER_CATEGORIES = [
  { code: '1a', file: 'pbp_b1a_inpat_hosp.txt', prefix: 'pbp_b1a', label: 'Inpatient Hospital-Acute' },
  { code: '1b', file: 'pbp_b1b_inpat_hosp.txt', prefix: 'pbp_b1b', label: 'Inpatient Hospital Psychiatric' },
  { code: '2', file: 'pbp_b2_snf.txt', prefix: 'pbp_b2', label: 'Skilled Nursing Facility (SNF)' },
];

// ---- small readers ------------------------------------------------------------------------
function q(row, col) {
  if (!(col in row)) throw new Error(`no column ${col}`);
  return row[col];
}

function cell(row, col) {
  const v = q(row, col);
  return `${col} "${v}"`;
}

// A NUM amount column: "1000.00" -> 1000. Blank -> null. Anything else is an error.
function amount(row, col, errors) {
  const v = q(row, col);
  if (v === '') return null;
  if (!/^\d+(\.\d{1,2})?$/.test(v)) { errors.push(`${col} "${v}" is not an amount`); return null; }
  return Number(v);
}

function yn(row, col, errors, allowBlank = true) {
  const v = q(row, col);
  if (v === '1' || v === '2' || (allowBlank && v === '')) return v;
  errors.push(`${col} "${v}" is not 1 (Yes) or 2 (No)${allowBlank ? ' or blank' : ''}`);
  return null;
}

function idFromName(s) {
  return s.toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

function pad3(seg) {
  return String(Number(seg)).padStart(3, '0');
}

// ---- accumulators (spec section 4.3) -------------------------------------------------------
// network_tier is always a tier_id of the document: IN, OUT or POS (decision N1,
// spec section 7.9), or null where the file does not say (7.3).
function tierSlot(tierId) {
  return (amt) => ({ amount: amt, currency: 'USD', network_tier: tierId, applies_to: 'medical' });
}

const inNetworkSlot = tierSlot('IN');
const outOfNetworkSlot = tierSlot('OUT');

// A deductible family with a Part B flag (in-network and out-of-network families).
// Returns { slot, note }.
function partBDeductible(d, fam, label, slotFn, errors) {
  const has = yn(d, `pbp_d_${fam}_deduct_yn`, errors);
  const partb = yn(d, `pbp_d_${fam}_deduct_partb_yn`, errors);
  const amt = amount(d, `pbp_d_${fam}_deduct_amt`, errors);
  const cells = [`pbp_d_${fam}_deduct_yn`, `pbp_d_${fam}_deduct_partb_yn`, `pbp_d_${fam}_deduct_amt`].map((c) => cell(d, c)).join(', ');
  if (has === '' || has === '2') {
    if (amt !== null) errors.push(`pbp_d_${fam}_deduct_amt has a value but pbp_d_${fam}_deduct_yn is "${has}"`);
    return { slot: null, note: has === '2' ? `${label}: the plan says it has none (${cells}); no slot is written.` : null };
  }
  if (partb === '1') {
    if (amt !== null) errors.push(`pbp_d_${fam}_deduct_amt has a value but the plan charges the Medicare-defined Part B deductible`);
    return {
      slot: null,
      note: `${label}: the plan charges the Medicare-defined Part B deductible amount, which the file does not state (${cells}); ` +
        'the slot needs an amount, so none is written (schema gap, spec section 9.1).',
    };
  }
  if (partb === '2' && amt !== null) return { slot: slotFn(amt), note: null };
  errors.push(`${label}: cannot read ${cells}`);
  return { slot: null, note: null };
}

// The PPO "annual plan deductible" family. pbp_d_ann_deduct_bens has positions
// for out-of-network non-Medicare-covered (1), in-network Medicare-covered (2)
// and in-network non-Medicare-covered (3) services, and none for out-of-network
// Medicare-covered services; pbp_d_ann_deduct_14a_yn asks about "your OON
// Medicare-covered Services Deductible", so that scope is always present.
// Decision 1 (spec section 7): a plan that declares an OUT tier and names no
// in-network scope gets the amount in oon_individual_deductible, network_tier
// OUT, with the scope list quoted. Any other combination with an out-of-network
// position, or a blank scope without an OUT tier, stays network_tier null.
function annualDeductibleOutOnly(d, c) {
  const bens = q(d, 'pbp_d_ann_deduct_bens');
  return !!c && q(c, 'pbp_c_oon_yn') === '1' && bens[1] !== '1' && bens[2] !== '1' &&
    q(d, 'pbp_d_ann_deduct_inn_mc_yn') !== '1' && q(d, 'pbp_d_ann_deduct_inn_nmc_yn') !== '1';
}

function annualDeductible(d, c, errors) {
  const cols = ['pbp_d_ann_deduct_yn', 'pbp_d_ann_deduct_amt_type', 'pbp_d_ann_deduct_amt', 'pbp_d_ann_deduct_bens',
    'pbp_d_ann_deduct_inn_mc_yn', 'pbp_d_ann_deduct_inn_nmc_yn', 'pbp_d_ann_deduct_oon_nmc_yn'];
  const cells = cols.map((col) => cell(d, col)).join(', ');
  const has = yn(d, 'pbp_d_ann_deduct_yn', errors, false);
  const type = q(d, 'pbp_d_ann_deduct_amt_type');
  const amt = amount(d, 'pbp_d_ann_deduct_amt', errors);
  if (has === '2') {
    if (type !== '' || amt !== null) errors.push(`annual deductible: pbp_d_ann_deduct_yn "2" but type or amount is filled (${cells})`);
    return { slot: null, notes: [`Annual plan deductible: the plan says it has none (${cell(d, 'pbp_d_ann_deduct_yn')}); no slot is written.`] };
  }
  if (has !== '1') return { slot: null, notes: [] };
  if (!DED_TYPES[type]) { errors.push(`pbp_d_ann_deduct_amt_type "${type}" is not a dictionary code`); return { slot: null, notes: [] }; }
  if (type !== '4') {
    if (amt !== null) errors.push(`annual deductible type ${type} (${DED_TYPES[type]}) carries an amount (${cells})`);
    return {
      slot: null,
      notes: [`Annual plan deductible: type ${type} "${DED_TYPES[type]}", which the file does not state as a dollar amount (${cells}); ` +
        'the slot needs an amount, so none is written (schema gap, spec section 9.1).'],
    };
  }
  if (amt === null) { errors.push(`annual deductible type 4 has no amount (${cells})`); return { slot: null, notes: [] }; }
  const bens = q(d, 'pbp_d_ann_deduct_bens');
  if (bens !== '' && !/^[01]{3}$/.test(bens)) { errors.push(`pbp_d_ann_deduct_bens "${bens}" is not a 3-position string`); return { slot: null, notes: [] }; }
  const oonBit = bens[0] === '1';
  const innBit = bens[1] === '1' || bens[2] === '1';
  if (innBit && !oonBit) {
    return {
      slot: inNetworkSlot(amt),
      notes: [`Annual plan deductible: $${amt}, scope in network only (${cells}); written as individual_deductible, network_tier IN.`],
    };
  }
  if (annualDeductibleOutOnly(d, c)) {
    const scope = [cell(d, 'pbp_d_ann_deduct_14a_yn'), cell(c, 'pbp_c_oon_mc_bendesc_cats')];
    if (oonBit) scope.push(cell(d, 'pbp_d_ann_deduct_oon_nmc_cats'));
    return {
      slot: tierSlot('OUT')(amt),
      slotName: 'oon_individual_deductible',
      notes: [`Annual plan deductible: $${amt}, written as oon_individual_deductible with network_tier OUT (decision 1, ` +
        'docs/specs/pbp-importer.md section 7). The plan declares an out-of-network benefit (pbp_c_oon_yn "1") and the ' +
        `deductible names no in-network scope: ${cells}. The deductible's service categories, verbatim: ${scope.join('; ')}. ` +
        'pbp_d_ann_deduct_14a_yn asks whether 14a preventive services are part of the out-of-network Medicare-covered ' +
        'services deductible; the categories are those of the plan\'s out-of-network benefit, less 14a when that answer is "2". ' +
        'Verified on H2406-013-000 against its 2027 Summary of Benefits; to be confirmed on 2 more PPO carriers.'],
    };
  }
  // Blank scope on a plan with no OUT tier, or a scope that names in-network and
  // out-of-network services: amount written, network unstated.
  const why = bens === ''
    ? 'The file does not say which network or services the deductible applies to (pbp_d_ann_deduct_bens is blank) and the plan declares no out-of-network benefit'
    : 'The scope names in-network and out-of-network services, so no single network slot fits';
  return {
    slot: { amount: amt, currency: 'USD', network_tier: null, applies_to: 'medical' },
    notes: [`Annual plan deductible: $${amt}, written as individual_deductible with network_tier null. ${why}. ` +
      `The file says: ${cells}; ${cell(d, 'pbp_d_ann_deduct_14a_yn')} refers to an out-of-network Medicare-covered services ` +
      'deductible (docs/specs/pbp-importer.md section 7).'],
  };
}

function buildAccumulators(d, c, planType, errors) {
  const acc = {};
  const notes = [];
  const add = (slotName, r) => {
    if (r.slot) acc[r.slotName || slotName] = r.slot;
    for (const n of [].concat(r.note || [], r.notes || [])) if (n) notes.push(n);
  };
  const posPlan = planType === '02';

  if (PPO_TYPES.has(planType)) {
    add('individual_deductible', annualDeductible(d, c, errors));
    for (const fam of ['inn', 'oon', 'comb']) {
      if (q(d, `pbp_d_${fam}_deduct_yn`) !== '') errors.push(`a PPO with pbp_d_${fam}_deduct_yn filled; the spec expects the annual family only`);
    }
  } else {
    if (q(d, 'pbp_d_ann_deduct_yn') !== '') errors.push('an HMO or HMO-POS with pbp_d_ann_deduct_yn filled; the spec expects the in-network family');
    if (q(d, 'pbp_d_inn_deduct_yn') === '') errors.push('pbp_d_inn_deduct_yn is blank');
    add('individual_deductible', partBDeductible(d, 'inn', 'In-network deductible', inNetworkSlot, errors));
    // Decision 4 (spec section 7): on an HMO-POS plan the out-of-network family
    // describes the point-of-service option.
    const oonDed = partBDeductible(d, 'oon', 'Out-of-network deductible', posPlan ? tierSlot('POS') : outOfNetworkSlot, errors);
    if (posPlan && oonDed.slot) {
      oonDed.note = 'Out-of-network deductible written as oon_individual_deductible with network_tier POS (decision 4, ' +
        'docs/specs/pbp-importer.md section 7): the plan is an HMO-POS and declares a point-of-service option, not an ' +
        'out-of-network benefit. The file says: ' +
        ['pbp_d_oon_deduct_yn', 'pbp_d_oon_deduct_partb_yn', 'pbp_d_oon_deduct_amt', 'pbp_d_oon_deduct_bens', 'pbp_d_oon_deduct_m_yn',
          'pbp_d_oon_deduct_m_cats', 'pbp_d_oon_deduct_nm_yn', 'pbp_d_oon_deduct_nm_cats'].map((col) => cell(d, col)).join(', ') +
        '. To be confirmed against the Aetna H1609-028 Summary of Benefits.';
    }
    add('oon_individual_deductible', oonDed);
    if (posPlan && c) {
      const posDed = ['pbp_c_pos_ded_yn', 'pbp_c_pos_ded_amt'].map((col) => cell(c, col));
      // Decision A5 (spec section 7.8): Section D is written; Section C is quoted,
      // and a disagreement is named.
      const dYes = q(d, 'pbp_d_oon_deduct_yn') === '1';
      const cYes = q(c, 'pbp_c_pos_ded_yn') === '1';
      const dAmt = q(d, 'pbp_d_oon_deduct_amt');
      const disagree = dYes !== cYes ? !(dYes && q(d, 'pbp_d_oon_deduct_partb_yn') === '1' && !cYes) : (dYes && dAmt !== q(c, 'pbp_c_pos_ded_amt'));
      notes.push(`Point-of-service deductible as Section C states it, verbatim: ${posDed.join(', ')}.` +
        (disagree ? ` Section C and Section D disagree (${cell(d, 'pbp_d_oon_deduct_yn')}, ${cell(d, 'pbp_d_oon_deduct_amt')}); ` +
          'Section D is written (decision A5, docs/specs/pbp-importer.md section 7.8).' : ''));
    }
    const comb = yn(d, 'pbp_d_comb_deduct_yn', errors);
    const combAmt = amount(d, 'pbp_d_comb_deduct_amt', errors);
    if (comb === '1') {
      notes.push('Combined in-network and out-of-network deductible, no Benefit Plan Standard slot (schema gap, spec section 9.1): ' +
        ['pbp_d_comb_deduct_yn', 'pbp_d_comb_deduct_partb_yn', 'pbp_d_comb_deduct_amt'].map((c) => cell(d, c)).join(', ') + '.');
    } else if (comb === '2') {
      notes.push(`Combined in-network and out-of-network deductible: the plan says it has none (${cell(d, 'pbp_d_comb_deduct_yn')}).`);
      if (combAmt !== null) errors.push('pbp_d_comb_deduct_amt has a value but pbp_d_comb_deduct_yn is "2"');
    }
  }

  // In-network MOOP.
  const moop = yn(d, 'pbp_d_out_pocket_amt_yn', errors, false);
  const moopAmt = amount(d, 'pbp_d_out_pocket_amt', errors);
  const moopType = q(d, 'pbp_d_out_pocket_amt_type');
  if (moop === '1') {
    if (moopAmt === null) errors.push('pbp_d_out_pocket_amt_yn "1" but no amount');
    else acc.individual_oop_max = inNetworkSlot(moopAmt);
    if (moopType !== '' && !MOOP_TYPES[moopType]) errors.push(`pbp_d_out_pocket_amt_type "${moopType}" is not a dictionary code`);
    notes.push(`In-network out-of-pocket maximum type, no Benefit Plan Standard field (schema gap, spec section 9.1): ${cell(d, 'pbp_d_out_pocket_amt_type')}` +
      (MOOP_TYPES[moopType] ? ` (${MOOP_TYPES[moopType]})` : '') + '.');
  } else if (moop === '2') {
    notes.push(`In-network out-of-pocket maximum: the plan says it has none (${cell(d, 'pbp_d_out_pocket_amt_yn')}); no slot is written.`);
  }

  // Combined (in and out of network) MOOP: no slot.
  const comb = yn(d, 'pbp_d_comb_max_enr_amt_yn', errors);
  const combType = q(d, 'pbp_d_comb_max_enr_amt_type');
  if (comb === '1') {
    if (amount(d, 'pbp_d_comb_max_enr_amt', errors) === null) errors.push('pbp_d_comb_max_enr_amt_yn "1" but no amount');
    notes.push('Combined in-network and out-of-network out-of-pocket maximum, no Benefit Plan Standard slot (schema gap, spec section 9.1): ' +
      `${cell(d, 'pbp_d_comb_max_enr_amt')}; ${cell(d, 'pbp_d_comb_max_enr_amt_type')}` +
      (MOOP_TYPES[combType] ? ` (${MOOP_TYPES[combType]})` : '') + '.');
  } else if (comb === '2') {
    notes.push(`Combined out-of-pocket maximum: the plan says it has none (${cell(d, 'pbp_d_comb_max_enr_amt_yn')}).`);
  }

  // Out-of-network MOOP.
  const oon = yn(d, 'pbp_d_oon_max_enr_oopc_yn', errors);
  if (oon === '1') {
    const a = amount(d, 'pbp_d_oon_max_enr_oopc_amt', errors);
    if (a === null) errors.push('pbp_d_oon_max_enr_oopc_yn "1" but no amount');
    else acc.oon_individual_oop_max = (posPlan ? tierSlot('POS') : outOfNetworkSlot)(a);
    if (posPlan && a !== null) {
      notes.push('Out-of-network out-of-pocket maximum written as oon_individual_oop_max with network_tier POS (decision 4, ' +
        'docs/specs/pbp-importer.md section 7). The file says: ' +
        ['pbp_d_oon_max_enr_oopc_yn', 'pbp_d_oon_max_enr_oopc_amt', 'pbp_d_oon_max_enr_oopc_bens', 'pbp_d_oon_max_enr_m_yn',
          'pbp_d_oon_max_enr_nm_yn'].map((col) => cell(d, col)).join(', ') +
        '. To be confirmed against the Aetna H1609-028 Summary of Benefits.');
    }
  }
  if (posPlan && c) {
    notes.push('Point-of-service maximum as Section C states it, verbatim: ' +
      ['pbp_c_pos_maxenr_oopc_yn', 'pbp_c_pos_maxenr_oopc_amt', 'pbp_c_pos_maxenr_oopc_per', 'pbp_c_pos_maxenr_oopc_per_d']
        .map((col) => cell(c, col)).join(', ') + '.');
  }

  // Schema order of the slots.
  const order = ['individual_deductible', 'family_deductible', 'individual_oop_max', 'family_oop_max',
    'oon_individual_deductible', 'oon_family_deductible', 'oon_individual_oop_max', 'oon_family_oop_max'];
  const accumulators = {};
  for (const k of order) if (acc[k]) accumulators[k] = acc[k];
  return { accumulators, notes };
}

// Every non-blank Section D cell of the deductible and out-of-pocket families,
// verbatim, in file order. Includes service-level and differential deductibles.
const ACCUMULATOR_PREFIXES = ['pbp_d_ann_deduct_', 'pbp_d_inn_deduct_', 'pbp_d_comb_deduct_', 'pbp_d_oon_deduct_',
  'pbp_d_non_deduct_', 'pbp_d_nmc_deduct_', 'pbp_d_diff_deduct_', 'pbp_d_mand_deduct_', 'pbp_d_deduct_',
  'pbp_d_out_pocket_', 'pbp_d_inn_max_enr_', 'pbp_d_comb_max_enr_', 'pbp_d_oon_max_enr_', 'pbp_d_maxenr_oopc_'];

function accumulatorCells(d) {
  return Object.keys(d)
    .filter((c) => ACCUMULATOR_PREFIXES.some((p) => c.startsWith(p)) && d[c] !== '')
    .map((c) => cell(d, c));
}

// ---- network tiers (spec section 4.2) ------------------------------------------------------
function buildTiers(c, hasOonRows, hasPosRows, hospital, errors) {
  const tiers = [{
    tier_id: 'IN',
    name: 'In-Network',
    description: 'The plan network. Cost sharing in the PBP Section B files (pbp_b*), which carry no network qualifier.',
    tier_class: 'network',
  }];
  const oonYn = c ? q(c, 'pbp_c_oon_yn') : '';
  const posYn = c ? q(c, 'pbp_c_pos_yn') : '';
  if (!['', '1', '2'].includes(oonYn)) errors.push(`pbp_c_oon_yn "${oonYn}" is not a dictionary code`);
  if (!['', '1', '2'].includes(posYn)) errors.push(`pbp_c_pos_yn "${posYn}" is not a dictionary code`);
  if (hasOonRows !== (oonYn === '1')) errors.push(`pbp_c_oon_yn "${oonYn}" but the plan has ${hasOonRows ? '' : 'no '}rows in pbp_Section_C_OON.txt`);
  if (hasPosRows !== (posYn === '1')) errors.push(`pbp_c_pos_yn "${posYn}" but the plan has ${hasPosRows ? '' : 'no '}rows in pbp_Section_C_POS.txt`);
  if (oonYn === '1') {
    tiers.push({
      tier_id: 'OUT',
      name: 'Out-of-Network',
      description: 'pbp_Section_C pbp_c_oon_yn "1". Cost sharing in pbp_Section_C (inpatient, SNF) and pbp_Section_C_OON (outpatient groups).',
      tier_class: 'network',
    });
  }
  if (posYn === '1') {
    tiers.push({
      tier_id: 'POS',
      name: 'Point-of-Service',
      description: 'pbp_Section_C pbp_c_pos_yn "1". Cost sharing in pbp_Section_C_POS (groups).',
      tier_class: 'network',
    });
  }
  for (const h of hospital) {
    const p = h.cat.prefix;
    const main = yn(h.row, `${p}_cost_vary_tiers_yn`, errors);
    const ad = yn(h.row, `${p}_ad_cost_vary_tiers_yn`, errors);
    if (main !== '1' && ad !== '1') continue;
    const mainNum = q(h.row, `${p}_cost_vary_tier_num`);
    const adNum = q(h.row, `${p}_ad_cost_vary_tier_num`);
    const low = q(h.row, `${p}_cost_vary_low_tier`);
    if (main === '1' && ad === '1' && mainNum !== adNum) errors.push(`${p}: ${mainNum} tiers for the stay but ${adNum} for additional days`);
    const num = main === '1' ? mainNum : adNum;
    if (!/^[23]$/.test(num)) { errors.push(`${p}: tier count "${num}" is not 2 or 3`); continue; }
    const cells = [`${p}_cost_vary_tiers_yn`, `${p}_cost_vary_tier_num`, `${p}_cost_vary_low_tier`, `${p}_ad_cost_vary_tiers_yn`, `${p}_ad_cost_vary_tier_num`]
      .map((col) => cell(h.row, col)).join(', ');
    const scope = main === '1' ? 'Medicare-covered stay' + (ad === '1' ? ' and additional days' : '') : 'additional days only';
    for (let t = 1; t <= Number(num); t++) {
      tiers.push({
        tier_id: `IN_${h.cat.code.toUpperCase()}_TIER_${t}`,
        name: `${h.cat.label}, cost-sharing tier ${t}`,
        description: `Service category ${h.cat.code}: cost sharing varies by the hospital or facility used (${scope}). ` +
          `${cells}${low === String(t) ? '; this is the lowest-cost tier' : ''}. The file does not name the facilities in each tier.`,
        tier_class: 'cost_designation',
        parent_tier_id: 'IN',
      });
    }
  }
  return tiers;
}

// ---- benefits (spec section 5) -------------------------------------------------------------
// fhir/pbp-crosswalk.json names, per BPS benefit, the PBP category code, the file
// and the columns read. Read once at load; buildDocument stays pure.
const CROSSWALK_FILE = path.join(REPO_ROOT, 'fhir', 'pbp-crosswalk.json');
const CROSSWALK = JSON.parse(fs.readFileSync(CROSSWALK_FILE, 'utf8'));
const BENEFIT_FILES = [...new Set(CROSSWALK.benefits.map((b) => b.file))];
const B_FILES = [...new Set([...HOSPITAL_TIER_CATEGORIES.map((c) => c.file), ...BENEFIT_FILES])].sort();
const READ_FILES = ['pbp_Section_A.txt', 'pbp_Section_C.txt', 'pbp_Section_C_OON.txt', 'pbp_Section_C_POS.txt', 'pbp_Section_D.txt',
  ...B_FILES, 'PlanArea.txt', 'PlanRegionArea.txt'];
const AMO = { 2: 'supplemental_mandatory', 3: 'supplemental_optional' };
const AMO_LABELS = { 2: 'Mandatory', 3: 'Optional', 4: 'Both' };
const WAIVER_UNITS = { 1: 'days', 2: 'hours' };
const INTERVALS = { 1: 0, 2: 1, 3: 2, 4: 3 };
const PEREAR = { 1: 'per_ear', 2: 'one_ear' };
const PEREAR_LABELS = { 1: 'Per ear', 2: 'One single ear', 3: 'Both ears combined' };
const IN_OON_LABELS = { 1: 'In-network services only', 2: 'Both in-network and out-of-network services' };
const STEP_ORDER = ['type', 'sequence', 'amount', 'amount_min', 'amount_max', 'rate', 'rate_min', 'rate_max', 'basis',
  'max_amount', 'max_basis', 'unit_range', 'applies_to_deductible', 'applies_to_moop', 'notes'];

// Column names of the out-of-network and point-of-service group files.
const GROUP_COLS = {
  OUT: {
    file: 'pbp_Section_C_OON.txt', id: 'pbp_c_oon_outpt_group_num_id', label: 'pbp_c_oon_outpt_grp_lbl', bens: 'pbp_c_oon_outpt_bendesc_ben',
    mc: 'pbp_c_oon_out_mc_bendesc_cats', nmc: 'pbp_c_oon_out_nmc_bendesc_cats',
    copay: { yn: 'pbp_c_oon_outpt_copay_yn', min: 'pbp_c_oon_outpt_copay_min_amt', max: 'pbp_c_oon_outpt_copay_max_amt' },
    coins: { yn: 'pbp_c_oon_outpt_coins_yn', min: 'pbp_c_oon_outpt_coins_min_pct', max: 'pbp_c_oon_outpt_coins_max_pct' },
    ded: { yn: 'pbp_c_oon_outpt_ded_yn', amt: 'pbp_c_oon_outpt_ded_amt' },
    maxplan: ['pbp_c_oon_outpt_maxplan_yn', 'pbp_c_oon_outpt_maxplan_amt', 'pbp_c_oon_outpt_maxplan_per', 'pbp_c_oon_outpt_maxplan_per_d'],
  },
  POS: {
    file: 'pbp_Section_C_POS.txt', id: 'pbp_c_pos_outpt_group_num_id', label: 'pbp_c_pos_group_lbl', bens: 'pbp_c_pos_oupt_bencat_bens',
    mc: 'pbp_c_pos_outpt_mc_bencats', nmc: 'pbp_c_pos_outpt_nmc_bencats',
    copay: { yn: 'pbp_c_pos_outpt_copay_yn', min: 'pbp_c_pos_outpt_copay_min_amt', max: 'pbp_c_pos_outpt_copay_max_amt' },
    coins: { yn: 'pbp_c_pos_outpt_coins_yn', min: 'pbp_c_pos_outpt_coins_min_pct', max: 'pbp_c_pos_outpt_coins_max_pct' },
    ded: { yn: 'pbp_c_pos_outpt_deduct_yn', amt: 'pbp_c_pos_outpt_deduct_amt' },
    maxplan: ['pbp_c_pos_outpt_maxplan_yn', 'pbp_c_pos_outpt_maxplan_amt', 'pbp_c_pos_outpt_maxplan_per', 'pbp_c_pos_outpt_maxplan_per_d'],
  },
};

function chosen(s, n) {
  return s[n - 1] === '1';
}

function cats(v) {
  return v.split(';').map((x) => x.trim()).filter(Boolean);
}

// A whole-percent column: "40" -> 40. Blank -> null.
function percent(row, col, errors) {
  const v = q(row, col);
  if (v === '') return null;
  if (!/^\d{1,3}$/.test(v) || Number(v) > 100) { errors.push(`${col} "${v}" is not a whole percent from 0 to 100`); return null; }
  return Number(v);
}

function dayNumber(row, col, errors) {
  const v = q(row, col);
  if (!/^\d{1,3}$/.test(v)) { errors.push(`${col} "${v}" is not a day number`); return null; }
  return Number(v);
}

function cellsOf(row, cols) {
  return cols.filter((col) => col && q(row, col) !== '').map((col) => cell(row, col));
}

function orderStep(s) {
  const o = {};
  for (const k of STEP_ORDER) if (s[k] !== undefined) o[k] = s[k];
  return o;
}

// A copay or coinsurance step from a "yn" column and its minimum and maximum
// columns (spec 5.5). Equal minimum and maximum give amount or rate; different
// ones give the v1.2.0 range fields. Returns { step, cells } or null.
function costStep(row, spec, kind, errors) {
  if (!spec) return null;
  const v = q(row, spec.yn);
  const cells = [cell(row, spec.yn)];
  if (v === '' || v === '2') return null;
  if (v !== '1' && v !== '3') { errors.push(`${spec.yn} "${v}" is not 1, 2 or 3`); return null; }
  if (spec.ehc) {
    const e = q(row, spec.ehc);
    cells.push(cell(row, spec.ehc));
    if (!/^[01]+$/.test(e)) { errors.push(`${spec.ehc} "${e}" is not a position string while ${spec.yn} is "${v}"`); return null; }
    if (!chosen(e, spec.position)) return null;
  }
  const read = kind === 'copay' ? amount : percent;
  const lo = read(row, spec.min, errors);
  const hi = read(row, spec.max, errors);
  cells.push(cell(row, spec.min), cell(row, spec.max));
  if (lo === null || hi === null) { errors.push(`${spec.yn} "${v}" but ${cells.slice(-2).join(', ')}`); return null; }
  if (lo > hi) { errors.push(`minimum above maximum: ${cells.slice(-2).join(', ')}`); return null; }
  const s = { type: kind };
  if (kind === 'copay') Object.assign(s, lo === hi ? { amount: lo } : { amount_min: lo, amount_max: hi });
  else Object.assign(s, lo === hi ? { rate: lo / 100 } : { rate_min: lo / 100, rate_max: hi / 100 });
  const notes = [];
  if (spec.basis) s.basis = spec.basis;
  if (spec.basis_col) {
    const b = q(row, spec.basis_col);
    cells.push(cell(row, spec.basis_col));
    if (spec.basis_codes[b]) s.basis = spec.basis_codes[b];
    else if (b === '3') notes.push(`Charged per ${cell(row, spec.basis_col)} (Other, Describe): ${cell(row, spec.basis_desc)}.`);
    else if (b !== '') errors.push(`${spec.basis_col} "${b}" is not a dictionary code`);
  }
  if (spec.max_amount && q(row, spec.max_amount) !== '') {
    const m = amount(row, spec.max_amount, errors);
    cells.push(cell(row, spec.max_amount));
    if (m !== null) { s.max_amount = m; s.max_basis = 'per_visit'; }
  }
  if (spec.waiver && q(row, spec.waiver.yn) === '1') {
    const w = spec.waiver;
    const unit = w.unit ? WAIVER_UNITS[q(row, w.unit)] : null;
    const num = w.num ? q(row, w.num) : '';
    const wc = cellsOf(row, [w.yn, w.unit, w.num]);
    cells.push(...wc);
    notes.push(`Waived if admitted to the hospital${num && unit ? ` within ${num} ${unit}` : ''} (${wc.join(', ')}).`);
  }
  if (notes.length) s.notes = notes.join(' ');
  return { step: s, cells };
}

// Decision S1 (spec section 7.12): a covered service whose copay and coinsurance
// answers are both "No" (yn 2, or yn 1 or 3 with this service's position not
// chosen in the shared "which services" column) costs the member nothing, and
// is written as a $0 copay step whose note quotes both answers. A deductible
// answered "No" still writes no slot (decision 2).
function answeredNo(row, spec) {
  if (!spec) return false;
  const v = q(row, spec.yn);
  if (v === '2') return true;
  return (v === '1' || v === '3') && !!spec.ehc && !chosen(q(row, spec.ehc), spec.position);
}

function noCostShareStep(row, copaySpec, coinsSpec) {
  if (!answeredNo(row, copaySpec) || !answeredNo(row, coinsSpec)) return null;
  const cells = cellsOf(row, [copaySpec.yn, copaySpec.ehc, coinsSpec.yn, coinsSpec.ehc]);
  return {
    step: {
      type: 'copay', amount: 0,
      notes: `The file states no copayment and no coinsurance for this service (${cells.join(', ')}); written as a $0 copay ` +
        '(decision S1, docs/specs/pbp-importer.md section 7.12).',
    },
    cells,
  };
}

// The category-level "Is there a deductible?" columns: a step of type deductible.
function serviceDeductibleStep(row, spec, errors) {
  if (!spec) return null;
  const v = q(row, spec.yn);
  if (v === '' || v === '2') return null;
  if (v !== '1') { errors.push(`${spec.yn} "${v}" is not 1 or 2`); return null; }
  const cells = [cell(row, spec.yn)];
  if (spec.ehc) {
    cells.push(cell(row, spec.ehc));
    if (!chosen(q(row, spec.ehc), spec.position)) return null;
  }
  const amt = amount(row, spec.amt, errors);
  cells.push(cell(row, spec.amt));
  if (amt === null) { errors.push(`${spec.yn} "1" but ${cell(row, spec.amt)}`); return null; }
  return {
    step: {
      type: 'deductible', amount: amt,
      notes: `Service-level deductible, separate from the plan deductible: ${cells.join(', ')}` +
        `${spec.shared ? `; the column covers service category ${spec.shared}` : ''}.`,
    },
    cells,
  };
}

// Day-interval steps (spec 5.5, inpatient): "number of intervals" code 1 to 4
// means 0 to 3 intervals; each has a value and a begin and end day.
function intervalSteps(row, kind, numCol, valCol, bgnCol, endCol, errors) {
  const code = q(row, numCol);
  if (code === '') return { steps: [], cells: [] };
  if (!(code in INTERVALS)) { errors.push(`${numCol} "${code}" is not a dictionary code`); return { steps: [], cells: [] }; }
  const steps = [];
  const cells = [cell(row, numCol)];
  for (let i = 1; i <= INTERVALS[code]; i++) {
    const val = kind === 'copay' ? amount(row, valCol(i), errors) : percent(row, valCol(i), errors);
    const from = dayNumber(row, bgnCol(i), errors);
    const to = dayNumber(row, endCol(i), errors);
    cells.push(cell(row, valCol(i)), cell(row, bgnCol(i)), cell(row, endCol(i)));
    if (val === null || from === null || to === null) { errors.push(`${numCol}: interval ${i} is incomplete`); continue; }
    if (from > to) { errors.push(`${numCol}: interval ${i} begins after it ends`); continue; }
    steps.push({ type: kind, ...(kind === 'copay' ? { amount: val } : { rate: val / 100 }), basis: 'per_day', unit_range: { from, to } });
  }
  return { steps, cells };
}

// A stay: an optional per-stay amount and day intervals. The per-stay amount is
// written when there are no intervals or when it is not 0 (spec 5.5; a $0
// per-stay amount beside day intervals is quoted in the tier notes only).
function stayCostShares(row, kind, cols, errors) {
  const out = { steps: [], cells: [], notes: [] };
  const stay = kind === 'copay' ? amount(row, cols.stay, errors) : percent(row, cols.stay, errors);
  if (q(row, cols.stay) !== '') out.cells.push(cell(row, cols.stay));
  const iv = intervalSteps(row, kind, cols.num, cols.val, cols.bgn, cols.end, errors);
  out.cells.push(...iv.cells);
  if (stay !== null && (iv.steps.length === 0 || stay > 0)) {
    out.steps.push({ type: kind, ...(kind === 'copay' ? { amount: stay } : { rate: stay / 100 }), basis: 'per_stay' });
  }
  out.steps.push(...iv.steps);
  return out;
}

// ---- deductible and maximum scopes (spec 5.5) ----------------------------------------------
// Each returns, per tier, a function of (code, medicare_covered) giving true,
// false or undefined (not stated), and a note for tiers where the deductible or
// maximum the flag refers to has no accumulator slot.
function listScope(allYn, list) {
  return (code) => (allYn === '1' ? true : cats(list).includes(code));
}

function deductibleScopes(d, c, planType, accumulators) {
  const scopes = {};
  const notes = {};
  const none = () => false;
  if (PPO_TYPES.has(planType)) {
    const has = q(d, 'pbp_d_ann_deduct_yn');
    if (has === '2') { scopes.IN = none; scopes.OUT = none; return { scopes, notes }; }
    if (has !== '1') return { scopes, notes };
    const bens = q(d, 'pbp_d_ann_deduct_bens');
    // Decision 1's reading of a blank scope is verified for an amount (type 4)
    // only; for the Medicare-defined types 1 to 3 the flags stay unwritten.
    if (bens === '' && q(d, 'pbp_d_ann_deduct_amt_type') !== '4') return { scopes, notes };
    const innMc = bens[1] === '1' ? listScope(q(d, 'pbp_d_ann_deduct_inn_mc_yn'), q(d, 'pbp_d_ann_deduct_inn_mc_cats')) : none;
    const innNmc = bens[2] === '1' ? listScope(q(d, 'pbp_d_ann_deduct_inn_nmc_yn'), q(d, 'pbp_d_ann_deduct_inn_nmc_cats')) : none;
    const oonNmc = bens[0] === '1' ? listScope(q(d, 'pbp_d_ann_deduct_oon_nmc_yn'), q(d, 'pbp_d_ann_deduct_oon_nmc_cats')) : none;
    scopes.IN = (code, mc) => (mc ? innMc(code) : innNmc(code));
    if (annualDeductibleOutOnly(d, c) && accumulators.oon_individual_deductible) {
      const oonMc = cats(q(c, 'pbp_c_oon_mc_bendesc_cats')).filter((x) => !(x === '14a' && q(d, 'pbp_d_ann_deduct_14a_yn') === '2'));
      scopes.OUT = (code, mc) => (mc ? oonMc.includes(code) : oonNmc(code));
    } else {
      scopes.OUT = (code, mc) => (mc ? undefined : oonNmc(code));
    }
    const type = q(d, 'pbp_d_ann_deduct_amt_type');
    if (type !== '4') {
      notes.IN = notes.OUT = `applies_to_deductible refers to the annual plan deductible, ${cell(d, 'pbp_d_ann_deduct_amt_type')} ` +
        `(${DED_TYPES[type] || 'not a dictionary code'}), which the file does not state as an amount, so no slot holds it.`;
    } else if (accumulators.individual_deductible && accumulators.individual_deductible.network_tier === null) {
      notes.IN = notes.OUT = 'applies_to_deductible refers to the annual plan deductible written as individual_deductible with network_tier null.';
    }
    return { scopes, notes };
  }
  // HMO and HMO-POS: in-network family for IN, out-of-network family for POS
  // (decision 4), and the combined family for both when filled.
  const family = (fam, mcPos, nmcPos, mYn, mCats, nmYn, nmCats) => {
    const has = q(d, `pbp_d_${fam}_deduct_yn`);
    if (has === '2') return none;
    if (has !== '1') return null;
    const bens = q(d, `pbp_d_${fam}_deduct_bens`);
    const mc = bens[mcPos - 1] === '1' ? listScope(q(d, mYn), q(d, mCats)) : none;
    const nmc = bens[nmcPos - 1] === '1' ? listScope(q(d, nmYn), q(d, nmCats)) : none;
    return (code, isMc) => (isMc ? mc(code) : nmc(code));
  };
  const inn = family('inn', 2, 1, 'pbp_d_inn_deduct_m_yn', 'pbp_d_inn_deduct_m_cats', 'pbp_d_inn_deduct_nm_yn', 'pbp_d_inn_deduct_nm_cats');
  const oon = family('oon', 2, 1, 'pbp_d_oon_deduct_m_yn', 'pbp_d_oon_deduct_m_cats', 'pbp_d_oon_deduct_nm_yn', 'pbp_d_oon_deduct_nm_cats');
  const combIn = family('comb', 2, 3, 'pbp_d_comb_deduct_inn_m_yn', 'pbp_d_comb_deduct_inn_m_cats', 'pbp_d_comb_deduct_inn_nm_yn', 'pbp_d_comb_deduct_inn_nm_cats');
  const combOut = family('comb', 4, 1, 'pbp_d_comb_deduct_oon_m_yn', 'pbp_d_comb_deduct_oon_m_cats', 'pbp_d_comb_deduct_oon_nm_yn', 'pbp_d_comb_deduct_oon_nm_cats');
  const either = (a, b) => {
    if (!a && !b) return undefined;
    return (code, mc) => {
      const x = a ? a(code, mc) : undefined;
      const y = b ? b(code, mc) : undefined;
      return x === true || y === true ? true : (x === false && (y === false || y === undefined) ? x : y);
    };
  };
  const combFilled = q(d, 'pbp_d_comb_deduct_yn') === '1';
  scopes.IN = either(inn, combFilled ? combIn : null);
  scopes.POS = either(oon, combFilled ? combOut : null);
  const why = [];
  if (q(d, 'pbp_d_inn_deduct_partb_yn') === '1') why.push('the in-network deductible is the Medicare-defined Part B deductible, which the file does not state');
  if (combFilled) why.push('the combined in-network and out-of-network deductible has no slot');
  if (why.length) notes.IN = `applies_to_deductible may refer to a deductible with no accumulator slot: ${why.join('; ')}.`;
  const whyPos = [];
  if (q(d, 'pbp_d_oon_deduct_partb_yn') === '1') whyPos.push('the out-of-network deductible is the Medicare-defined Part B deductible, which the file does not state');
  if (combFilled) whyPos.push('the combined in-network and out-of-network deductible has no slot');
  if (whyPos.length) notes.POS = `applies_to_deductible may refer to a deductible with no accumulator slot: ${whyPos.join('; ')}.`;
  return { scopes, notes };
}

function moopScopes(d, planType, accumulators) {
  const scopes = {};
  const notes = {};
  const none = () => false;
  const fromBens = (bens, mcPos, nmcPos, mYn, mCats, nmYn, nmCats) => {
    const mc = bens[mcPos - 1] === '1' ? listScope(q(d, mYn), q(d, mCats)) : none;
    const nmc = bens[nmcPos - 1] === '1' ? listScope(q(d, nmYn), q(d, nmCats)) : none;
    return (code, isMc) => (isMc ? mc(code) : nmc(code));
  };
  if (q(d, 'pbp_d_out_pocket_amt_yn') === '1') {
    scopes.IN = fromBens(q(d, 'pbp_d_inn_max_enr_oopc_bens'), 2, 1, 'pbp_d_inn_max_enr_m_yn', 'pbp_d_inn_max_enr_m_cat_ex',
      'pbp_d_inn_max_enr_nm_yn', 'pbp_d_inn_max_enr_nm_cat_ex');
  }
  const outTier = PPO_TYPES.has(planType) ? 'OUT' : (planType === '02' ? 'POS' : null);
  if (outTier) {
    if (q(d, 'pbp_d_oon_max_enr_oopc_yn') === '1' && accumulators.oon_individual_oop_max) {
      scopes[outTier] = fromBens(q(d, 'pbp_d_oon_max_enr_oopc_bens'), 2, 1, 'pbp_d_oon_max_enr_m_yn', 'pbp_d_oon_max_enr_m_cat_ex',
        'pbp_d_oon_max_enr_nm_yn', 'pbp_d_oon_max_enr_nm_cat_ex');
    } else if (q(d, 'pbp_d_comb_max_enr_amt_yn') === '1') {
      scopes[outTier] = fromBens(q(d, 'pbp_d_comb_max_enr_oopc_bens'), 4, 1, 'pbp_d_comb_max_enr_oon_m_yn', 'pbp_d_comb_max_enr_oon_mcat_ex',
        'pbp_d_comb_max_enr_oon_nm_yn', 'pbp_d_comb_max_enr_oon_nmcatex');
      notes[outTier] = `applies_to_moop refers to the combined in-network and out-of-network maximum (${cell(d, 'pbp_d_comb_max_enr_amt')}), ` +
        'which has no accumulator slot (spec section 9.1).';
    }
  }
  return { scopes, notes };
}

// ---- out-of-network and point-of-service groups ----------------------------------------------
function groupsFor(rows, tierId) {
  const g = GROUP_COLS[tierId];
  return rows.map((r) => ({ row: r, id: q(r, g.id), label: q(r, g.label), mc: cats(q(r, g.mc)), nmc: cats(q(r, g.nmc)) }));
}

// The tier row for one benefit from the groups that list its category code.
function groupTierRow(tierId, b, groups, errors, warn) {
  const g = GROUP_COLS[tierId];
  const hits = groups.filter((x) => (b.medicare_covered ? x.mc : x.nmc).includes(b.pbp_code));
  if (!hits.length) return null;
  const priced = hits.filter((x) => q(x.row, g.copay.yn) !== '' || q(x.row, g.coins.yn) !== '' || q(x.row, g.ded.yn) !== '');
  if (priced.length > 1) warn('service-in-more-than-one-group', `${tierId} ${b.pbp_code} in groups ${priced.map((x) => x.id).join(', ')}`);
  const steps = [];
  const notes = [];
  for (const x of hits) {
    const cells = [];
    const ded = serviceDeductibleStep(x.row, g.ded, errors);
    const cp = costStep(x.row, g.copay, 'copay', errors);
    const co = costStep(x.row, g.coins, 'coinsurance', errors);
    const none = noCostShareStep(x.row, g.copay, g.coins);
    for (const r of [ded, cp, co, none]) if (r) { steps.push(r.step); }
    cells.push(...cellsOf(x.row, [g.copay.yn, g.copay.min, g.copay.max, g.coins.yn, g.coins.min, g.coins.max, g.ded.yn, g.ded.amt, ...g.maxplan]));
    notes.push(`${g.file} group ${x.id} (label "${x.label}", ${cell(x.row, b.medicare_covered ? g.mc : g.nmc)}): ${cells.join(', ')}`);
  }
  return { steps, notes: notes.join('; ') + '.' };
}

// Section C inpatient-acute stay for the out-of-network (oon) or point-of-service (pos) tier.
function sectionCInpatient(c, kind, errors) {
  const p = `pbp_c_${kind}`;
  const out = { steps: [], cells: [], notes: [] };
  const take = (yesCol, typeCol, mcCostCol, costKind, cols) => {
    if (q(c, yesCol) !== '1' || !chosen(q(c, typeCol), 2)) return;
    out.cells.push(cell(c, yesCol), cell(c, typeCol));
    if (q(c, mcCostCol) === '1') {
      out.notes.push(`The plan charges the Medicare-defined ${costKind} for the stay, which the file does not state (${cell(c, mcCostCol)}; spec section 9.1).`);
      return;
    }
    const r = stayCostShares(c, costKind, cols, errors);
    out.steps.push(...r.steps);
    out.cells.push(...r.cells);
  };
  take(`${p}_coins_ihs_yn`, `${p}_coins_ihs_ben_type`, `${p}_coins_iha_mc_cost_yn`, 'coinsurance', {
    stay: `${p}_coins_iha_pct`, num: `${p}_coins_iha_intrvl_num`,
    val: (i) => `${p}_coins_iha_pct_i${i}`, bgn: (i) => `${p}_coins_iha_bgnd_i${i}`, end: (i) => `${p}_coins_iha_endd_i${i}`,
  });
  take(`${p}_copay_ihs_yn`, `${p}_copay_ihs_ben_type`, `${p}_copay_iha_mc_cost_yn`, 'copay', {
    stay: `${p}_copay_iha_ps_amt`, num: `${p}_copay_iha_intrvl_num`,
    val: (i) => `${p}_copay_iha_amt_i${i}`, bgn: (i) => `${p}_copay_iha_bgnd_i${i}`, end: (i) => `${p}_copay_iha_endd_i${i}`,
  });
  const none = noCostShareStep(c, { yn: `${p}_copay_ihs_yn`, ehc: `${p}_copay_ihs_ben_type`, position: 2 },
    { yn: `${p}_coins_ihs_yn`, ehc: `${p}_coins_ihs_ben_type`, position: 2 });
  if (none) out.steps.push(none.step);
  const dedYn = kind === 'oon' ? 'pbp_c_oon_ihs_ded_yn' : 'pbp_c_pos_ihs_ded_yn';
  const dedType = kind === 'oon' ? 'pbp_c_oon_ihs_ded_cost_type' : 'pbp_c_pos_ihs_ded_type';
  const dedCols = kind === 'oon' ? ['pbp_c_oon_ihs_ded_comb_amt', 'pbp_c_oon_ihs_ded_acu_amt'] : ['pbp_c_pos_comb_ded_amt', 'pbp_c_pos_iha_ded_amt'];
  if (q(c, dedYn) === '1') {
    const t = q(c, dedType);
    const col = chosen(t, 1) ? dedCols[0] : (chosen(t, 2) ? dedCols[1] : null);
    if (col) {
      const amt = amount(c, col, errors);
      if (amt === null) errors.push(`${dedYn} "1" but ${cell(c, col)}`);
      else {
        out.steps.unshift({ type: 'deductible', amount: amt, notes: `Service-level deductible for the stay, separate from the plan deductible: ${cellsOf(c, [dedYn, dedType, col]).join(', ')}.` });
      }
    }
  }
  return out;
}

// ---- one benefit ------------------------------------------------------------------------------
// Deductible steps first, then copay and coinsurance in the order read.
function sequence(steps) {
  const ordered = [...steps.filter((s) => s.type === 'deductible'), ...steps.filter((s) => s.type !== 'deductible')];
  return ordered.map((s, i) => ({ ...s, sequence: i + 1 }));
}

function flagSteps(steps, tierKey, b, ctx) {
  const ded = ctx.ded.scopes[tierKey];
  const moop = ctx.moop.scopes[tierKey];
  return steps.map((s) => {
    if (s.type === 'deductible') return orderStep(s);
    const out = { ...s };
    const dv = ded ? ded(b.pbp_code, b.medicare_covered) : undefined;
    const mv = moop ? moop(b.pbp_code, b.medicare_covered) : undefined;
    if (typeof dv === 'boolean') out.applies_to_deductible = dv;
    if (typeof mv === 'boolean') out.applies_to_moop = mv;
    return orderStep(out);
  });
}

function tierRow(tierId, tierKey, b, r, ctx) {
  const steps = flagSteps(sequence(r.steps), tierKey, b, ctx);
  const notes = [r.notes];
  if (steps.some((s) => s.applies_to_deductible === true) && ctx.ded.notes[tierKey]) notes.push(ctx.ded.notes[tierKey]);
  if (steps.some((s) => s.applies_to_moop !== undefined) && ctx.moop.notes[tierKey]) notes.push(ctx.moop.notes[tierKey]);
  const row = { tier_id: tierId, covered: true, cost_shares: steps };
  const text = notes.filter(Boolean).join(' ');
  if (text) row.notes = text;
  return row;
}

function inNetworkCostShares(b, row, errors) {
  const steps = [];
  const cells = [];
  for (const r of [serviceDeductibleStep(row, b.service_deductible, errors), costStep(row, b.copay, 'copay', errors),
    costStep(row, b.coins, 'coinsurance', errors), noCostShareStep(row, b.copay, b.coins)]) {
    if (r) { steps.push(r.step); }
  }
  for (const spec of [b.copay, b.coins, b.service_deductible]) {
    if (spec) cells.push(...cellsOf(row, [spec.yn, spec.ehc, spec.min, spec.max, spec.amt, spec.basis_col, spec.max_amount]));
  }
  return { steps, cells };
}

function periodOf(row, perCol, perDCol, errors) {
  const v = q(row, perCol);
  if (!(v in CROSSWALK.periodicity)) { errors.push(`${perCol} "${v}" is not a periodicity code`); return { ok: false }; }
  return { ok: true, period: CROSSWALK.periodicity[v], label: CROSSWALK.periodicity_labels[v], desc: perDCol ? q(row, perDCol) : '' };
}

function buildLimits(b, row, errors) {
  const limits = [];
  for (const l of b.limits || []) {
    if (l.kind === 'quantity') {
      const lim = q(row, l.lim);
      if (lim === '' || lim === '1') continue;
      if (lim !== '2') { errors.push(`${l.lim} "${lim}" is not 1 or 2`); continue; }
      const n = q(row, l.num);
      if (!/^\d+$/.test(n)) { errors.push(`${l.lim} "2" but ${cell(row, l.num)}`); continue; }
      const p = periodOf(row, l.per, l.per_d, errors);
      if (!p.ok) continue;
      limits.push({ type: l.type, value: Number(n), period: p.period,
        raw_text: `${cellsOf(row, [l.lim, l.num, l.per, l.per_d]).join(', ')} (${p.label}).` });
    } else if (l.kind === 'dollars') {
      const v = q(row, l.yn);
      if (v !== '1') { if (!['', '2'].includes(v)) errors.push(`${l.yn} "${v}" is not 1 or 2`); continue; }
      // A maximum that the file says is the one of another category (hearing
      // aids "Covered under Hearing Exams Category (18a)"): that category's
      // amount, with a shared_limit_id (v1.2.0) on both benefits.
      const via = l.via && q(row, l.type_col) === l.via.when ? l.via : null;
      const src = via || l;
      if (via && q(row, via.yn) !== '1') { errors.push(`${cell(row, l.type_col)} but ${cell(row, via.yn)}`); continue; }
      const amt = amount(row, src.amt, errors);
      if (amt === null) { errors.push(`${src.yn} "1" but ${cell(row, src.amt)}`); continue; }
      const p = periodOf(row, src.per, src.per_d, errors);
      if (!p.ok) continue;
      const lim = { type: 'dollars', value: amt, period: p.period };
      const shared = via ? via.shared_limit_id : (l.shared_when && q(row, l.shared_when.col) === l.shared_when.value ? l.shared_when.shared_limit_id : null);
      if (shared) lim.shared_limit_id = shared;
      const extra = [];
      if (via) extra.push(`${cell(row, l.yn)}, ${cell(row, l.type_col)} (Covered under Hearing Exams Category (18a)), so the amount is the 18a maximum`);
      if (l.perear) {
        const e = q(row, l.perear);
        if (PEREAR[e]) lim.scope = PEREAR[e];
        if (e !== '') extra.push(`${cell(row, l.perear)} (${PEREAR_LABELS[e] || 'not a dictionary code'})`);
      }
      if (l.in_oon && q(row, l.in_oon) !== '') extra.push(`${cell(row, l.in_oon)} (${IN_OON_LABELS[q(row, l.in_oon)] || 'not a dictionary code'})`);
      if (!via && l.type_col && q(row, l.type_col) !== '') extra.push(cell(row, l.type_col));
      if (shared && !via) extra.push(`${cell(row, l.shared_when.col)}: hearing aids are covered under this maximum`);
      lim.raw_text = `Maximum plan benefit coverage: ${cellsOf(row, [src.yn, src.amt, src.per, src.per_d]).join(', ')} (${p.label})` +
        `${extra.length ? '; ' + extra.join('; ') : ''}${src.shared ? `; the columns cover ${src.shared}` : ''}.`;
      limits.push(lim);
    }
  }
  return limits;
}

function buildConditions(b, row, errors) {
  const out = [];
  for (const [col, type, text] of [[b.auth, 'authorization', 'Authorization required'], [b.refer, 'referral', 'Referral required']]) {
    if (!col) continue;
    const v = q(row, col);
    if (v === '1') out.push({ type, description: `${text} (${cell(row, col)}).` });
    else if (!['', '2'].includes(v)) errors.push(`${col} "${v}" is not 1 or 2`);
  }
  return out;
}

// Inpatient acute (1a): per hospital cost tier, the Medicare-covered stay and
// the additional days (spec 5.5). Returns the in-network tier rows and limits.
function inpatientInNetwork(b, row, ctx, errors) {
  const p = b.prefix;
  const vary = q(row, `${p}_cost_vary_tiers_yn`) === '1' || q(row, `${p}_ad_cost_vary_tiers_yn`) === '1';
  const n = vary ? Number(q(row, `${p}_cost_vary_tiers_yn`) === '1' ? q(row, `${p}_cost_vary_tier_num`) : q(row, `${p}_ad_cost_vary_tier_num`)) : 1;
  const addDays = chosen(q(row, `${p}_bendesc_ad_up_nmcs`), 2);
  const rows = [];
  for (let t = 1; t <= n; t++) {
    const tierId = vary ? `IN_${b.pbp_code.toUpperCase()}_TIER_${t}` : 'IN';
    const steps = [];
    const cells = [];
    const notes = [];
    if (q(row, `${p}_ded_yn`) === '1') {
      const dedCells = [cell(row, `${p}_ded_yn`), cell(row, `${p}_ded_amt_t${t}`)];
      const mcCost = [`${p}_mc_copay_cstshr_yn_t${t}`, `${p}_mc_coins_cstshr_yn_t${t}`].filter((col) => q(row, col) === '1');
      const amt = amount(row, `${p}_ded_amt_t${t}`, errors);
      if (amt !== null) steps.push({ type: 'deductible', amount: amt, notes: `Service-level deductible, separate from the plan deductible: ${dedCells.join(', ')}.` });
      else if (mcCost.length) {
        // On every such plan the stay is charged the Medicare-defined cost share,
        // whose amounts the file does not state (spec section 7).
        notes.push(`The stay has a deductible with no amount in the file (${dedCells.join(', ')}), beside the Medicare-defined cost share ` +
          `(${mcCost.map((col) => cell(row, col)).join(', ')}); no step is written (spec section 9.1).`);
      } else errors.push(`${p}_ded_yn "1" but ${dedCells[1]}`);
    }
    for (const kind of ['copay', 'coinsurance']) {
      const k = kind === 'copay' ? 'copay' : 'coins';
      const v = q(row, `${p}_${k}_yn`);
      if (v !== '1') { if (!['', '2'].includes(v)) errors.push(`${p}_${k}_yn "${v}" is not 1 or 2`); continue; }
      cells.push(cell(row, `${p}_${k}_yn`));
      const mcCost = `${p}_mc_${k}_cstshr_yn_t${t}`;
      if (q(row, mcCost) === '1') {
        notes.push(`The plan charges the Medicare-defined ${kind} for the stay, which the file does not state (${cell(row, mcCost)}; spec section 9.1).`);
      } else {
        const stayCol = kind === 'copay' ? `${p}_copay_mcs_amt_t${t}` : `${p}_coins_mcs_pct_t${t}`;
        const valName = kind === 'copay' ? 'amt' : 'pct';
        const r = stayCostShares(row, kind, {
          stay: stayCol, num: `${p}_${k}_mcs_int_num_t${t}`,
          val: (i) => `${p}_${k}_mcs_${valName}_int${i}_t${t}`, bgn: (i) => `${p}_${k}_mcs_bgnd_int${i}_t${t}`, end: (i) => `${p}_${k}_mcs_endd_int${i}_t${t}`,
        }, errors);
        steps.push(...r.steps);
        cells.push(...r.cells);
      }
      if (addDays) {
        const iv = intervalSteps(row, kind, `${p}_${k}_ad_intrvl_num_t${t}`,
          (i) => `${p}_${k}_ad_${kind === 'copay' ? 'amt' : 'pct'}_int${i}_t${t}`, (i) => `${p}_${k}_ad_bgnd_int${i}_t${t}`, (i) => `${p}_${k}_ad_endd_int${i}_t${t}`, errors);
        for (const s of iv.steps) s.notes = `Additional days (1a1, supplemental): ${cell(row, `${p}_bendesc_amo_ad`)} (${AMO_LABELS[q(row, `${p}_bendesc_amo_ad`)] || 'not a dictionary code'}), ${cell(row, `${p}_bendesc_lim_ad`)}.`;
        steps.push(...iv.steps);
        cells.push(...iv.cells);
      }
    }
    const none = noCostShareStep(row, { yn: `${p}_copay_yn` }, { yn: `${p}_coins_yn` });
    if (none) { steps.push(none.step); cells.push(...none.cells); }
    const r = tierRow(tierId, 'IN', b, { steps, notes: [`${b.file} cells: ${cells.join(', ')}.`, ...notes].join(' ') }, ctx);
    rows.push(r);
  }
  const limits = [];
  if (addDays && q(row, `${p}_bendesc_lim_ad`) === '2') {
    const n2 = q(row, `${p}_bendesc_amt_ad`);
    if (!/^\d+$/.test(n2)) errors.push(`${p}_bendesc_lim_ad "2" but ${cell(row, `${p}_bendesc_amt_ad`)}`);
    else limits.push({ type: 'days', value: Number(n2), period: 'per_benefit_period',
      raw_text: `Additional days (1a1): ${cellsOf(row, [`${p}_bendesc_lim_ad`, `${p}_bendesc_amt_ad`]).join(', ')}.` });
  }
  return { rows, limits };
}

function buildBenefit(b, rows, ctx, errors, warn) {
  const row = rows.b[b.file];
  if (!row) { errors.push(`no ${b.file} row for ${b.benefit_id}`); return null; }
  const networkTiers = ctx.tiers.filter((t) => t.tier_class === 'network').map((t) => t.tier_id);
  const refs = [];
  let coverage_basis = 'medicare_covered';
  let covered = true;
  let notCoveredWhy = null;
  if (!b.medicare_covered) {
    const o = b.offered;
    const v = q(row, o.yn);
    if (v === '') { warn('supplemental-offer-blank', `${b.benefit_id} ${cell(row, o.yn)}`); return null; }
    if (v !== '1' && v !== '2') { errors.push(`${o.yn} "${v}" is not 1 or 2`); return null; }
    const isChosen = v === '1' && chosen(q(row, o.ehc), o.position);
    if (!isChosen) {
      if (o.when_not_chosen === 'skip' || (o.when_not_chosen === 'skip_unless_excluded' && v === '1')) return null;
      covered = false;
      coverage_basis = null;
      notCoveredWhy = v === '2' ? `${cell(row, o.yn)}: the plan does not offer this supplemental benefit` :
        `${cell(row, o.yn)}, ${cell(row, o.ehc)}: position ${o.position} not chosen`;
    } else {
      const amo = q(row, b.amo);
      coverage_basis = AMO[amo] || null;
      if (amo === '4') refs.push(`Coverage basis not written: ${cell(row, b.amo)} (Both mandatory and optional; question H1).`);
      else if (!AMO[amo]) { errors.push(`${b.amo} "${amo}" is not 2, 3 or 4`); return null; }
    }
  }
  const benefit = {
    benefit_id: b.benefit_id,
    benefit_type: b.benefit_type,
    coverage_basis,
    category: b.category,
    service_name: b.service_name,
  };
  if (b.canonical_key) benefit.canonical_key = b.canonical_key;
  benefit.raw_label = b.pbp_label;
  if (!covered) {
    benefit.network_cost_shares = networkTiers.map((t) => ({ tier_id: t, covered: false, cost_shares: [], notes: `${notCoveredWhy}.` }));
    benefit.limits = [];
    benefit.conditions = [];
    benefit.source_references = [{ excerpt: `PBP service category ${b.pbp_label} (${b.file}); not covered: ${notCoveredWhy}.` }];
    return benefit;
  }
  // A Medicare-covered category with no copay and no coinsurance answer (the
  // Part A categories of a Part B-only plan, pbp_a_ben_cov "2") is not written:
  // the file does not say the plan covers it (spec 5.4).
  const answerCols = b.handler === 'inpatient_acute' ? [`${b.prefix}_copay_yn`, `${b.prefix}_coins_yn`] : [b.copay, b.coins].filter(Boolean).map((s) => s.yn);
  if (b.medicare_covered && answerCols.every((col) => q(row, col) === '')) {
    warn('medicare-covered-cost-share-blank', `${b.benefit_id} (${cell(rows.a, 'pbp_a_ben_cov')})`);
    ctx.skipped.push(`${b.pbp_label} (${answerCols.map((col) => cell(row, col)).join(', ')})`);
    return null;
  }
  const ncs = [];
  let limits = [];
  if (b.handler === 'inpatient_acute') {
    const r = inpatientInNetwork(b, row, ctx, errors);
    ncs.push(...r.rows);
    limits = r.limits;
  } else {
    const r = inNetworkCostShares(b, row, errors);
    ncs.push(tierRow('IN', 'IN', b, { steps: r.steps, notes: `${b.file} cells: ${r.cells.join(', ')}.` }, ctx));
    limits = buildLimits(b, row, errors);
  }
  for (const tierId of ['OUT', 'POS']) {
    if (!networkTiers.includes(tierId)) continue;
    if (b.handler === 'inpatient_acute') {
      const kind = tierId === 'OUT' ? 'oon' : 'pos';
      const listCol = tierId === 'OUT' ? 'pbp_c_oon_mc_bendesc_cats' : 'pbp_c_pos_mc_bendesc_subcats';
      if (!rows.c || !cats(q(rows.c, listCol)).includes(b.pbp_code)) continue;
      const r = sectionCInpatient(rows.c, kind, errors);
      ncs.push(tierRow(tierId, tierId, b, {
        steps: r.steps, notes: [`pbp_Section_C (${listCol} lists ${b.pbp_code}): ${r.cells.join(', ')}.`, ...r.notes].join(' '),
      }, ctx));
      continue;
    }
    const r = groupTierRow(tierId, b, tierId === 'OUT' ? ctx.oonGroups : ctx.posGroups, errors, warn);
    if (r) ncs.push(tierRow(tierId, tierId, b, r, ctx));
    else if (tierId === 'OUT' && rows.c && cats(q(rows.c, b.medicare_covered ? 'pbp_c_oon_mc_bendesc_cats' : 'pbp_c_oon_nmc_bendesc_cats')).includes(b.pbp_code)) {
      warn('oon-category-without-group', `${b.benefit_id} ${b.pbp_code}`);
    }
  }
  // Decision 5 (spec section 7.13): emergency and urgent care are priced once,
  // with no network, and no out-of-network or point-of-service group lists them.
  const others = networkTiers.filter((t) => t !== 'IN');
  if (b.in_network_only_note && others.length && ncs.length === 1 && ncs[0].tier_id === 'IN') {
    const groupFile = others.map((t) => GROUP_COLS[t].file).join(' or ');
    ncs[0].notes = `${ncs[0].notes ? ncs[0].notes + ' ' : ''}${b.file} prices ${b.pbp_code} once, with no network, and no ${groupFile} group ` +
      `lists ${b.pbp_code}, so the cost share is written on the in-network tier only (decision 5, docs/specs/pbp-importer.md section 7.13).`;
  }
  benefit.network_cost_shares = ncs;
  benefit.limits = limits;
  benefit.conditions = buildConditions(b, row, errors);
  const quoted = cellsOf(row, b.quote || []);
  if (quoted.length) refs.push(`Values with no Benefit Plan Standard field, verbatim: ${quoted.join('; ')}.`);
  benefit.source_references = [{ excerpt: `PBP service category ${b.pbp_label} (${b.file}), mapped by fhir/pbp-crosswalk.json` +
    `${b.canonical_key ? '' : '; no canonical key, carried by name (spec section 9.1)'}.` }, ...refs.map((excerpt) => ({ excerpt }))];
  return benefit;
}

function buildBenefits(rows, ctx, errors, warn) {
  const out = [];
  for (const b of CROSSWALK.benefits) {
    const benefit = buildBenefit(b, rows, ctx, errors, warn);
    if (benefit) out.push(benefit);
  }
  return out;
}

// ---- service area -------------------------------------------------------------------------
// PlanArea.county_code is the SSA state and county code, not FIPS (spec section
// 4.1), so fips is null and the code goes to source_references.
function buildServiceArea(areaRows, regionRows, year, errors) {
  const years = new Set([...areaRows, ...regionRows].map((r) => r.contract_year));
  if (years.size !== 1) errors.push(`contract_year values ${[...years].join(', ') || '(none)'}: expected exactly 1`);
  const planYear = years.size === 1 ? Number([...years][0]) : null;
  if (planYear !== null && planYear !== year) errors.push(`contract_year ${planYear} is not --year ${year}`);
  const counties = new Map();
  for (const r of areaRows) {
    if (!/^\d{5}$/.test(r.county_code)) errors.push(`county_code "${r.county_code}" is not 5 digits`);
    const k = r.county_code;
    const prev = counties.get(k);
    const entry = prev || { code: k, name: r.county, state: r.stcd, partial: new Set(), eghp: new Set() };
    if (prev && (prev.name !== r.county || prev.state !== r.stcd)) errors.push(`county_code ${k} has 2 names`);
    entry.partial.add(r.partial_flag);
    entry.eghp.add(r.eghp_flag);
    counties.set(k, entry);
  }
  const list = [...counties.values()].sort((a, b) => (a.code < b.code ? -1 : 1));
  const states = [...new Set(list.map((c) => c.state))];
  const regions = [...new Set(regionRows.map((r) => `${r.ma_or_pdp_region_code} "${r.region}" (region_type "${r.region_type}")`))];
  let service_area = null;
  if (list.length) {
    service_area = {
      state: states.length === 1 ? states[0] : null,
      counties: list.map((c) => ({ name: c.name, fips: null })),
    };
  }
  const parts = [];
  if (list.length) {
    parts.push(`Service area from PlanArea.txt, ${list.length} ${list.length === 1 ? 'county' : 'counties'} in ${states.join(', ')}. ` +
      'county_code is the SSA state and county code, not FIPS, so service_area.counties[].fips is null. ' +
      'Each county as county_code, county, stcd, and the partial_flag and eghp_flag values on its rows: ' +
      list.map((c) => `${c.code} ${c.name} ${c.state} partial_flag ${[...c.partial].map((v) => `"${v}"`).join('/')} ` +
        `eghp_flag ${[...c.eghp].map((v) => `"${v}"`).join('/')}`).join('; ') + '.');
    if (states.length > 1) parts.push('The service area spans more than 1 state; service_area.state holds 1 state, so it is null (schema gap, spec section 9.1).');
  }
  if (regions.length) parts.push(`Service area from PlanRegionArea.txt (regions, no counties; schema gap, spec section 9.1): ${regions.join('; ')}.`);
  return { service_area, planYear, excerpt: parts.join(' ') || null };
}

// ---- document --------------------------------------------------------------------------------
const SECTION_A_UNCARRIED = ['bid_id', 'version', 'orgtype', 'pbp_a_org_name', 'pbp_a_org_type', 'pbp_a_ben_cov',
  'pbp_a_network_flag', 'pbp_a_plan_geog_name', 'pbp_a_segment_name', 'pbp_a_eghp_yn', 'pbp_a_special_need_flag',
  'pbp_a_special_need_plan_type', 'pbp_a_snp_institutional_type', 'pbp_a_snp_cond', 'pbp_a_snp_pct',
  'pbp_a_dsnp_zerodollar', 'pbp_a_snp_state_cvg_yn', 'pbp_a_contract_partd_flag', 'pbp_a_hospice_care_yn',
  'pbp_a_continue_yn', 'pbp_a_org_website', 'pbp_a_phys_web_addr', 'pbp_a_formulary_web_addr', 'pbp_a_pharmacy_website'];

function planIdFor(a, keyText) {
  const suffix = '_' + keyText.replace(/-/g, '_');
  let name = idFromName(a.pbp_a_plan_name);
  while (name.length + suffix.length > 64 && name.includes('_')) name = name.slice(0, name.lastIndexOf('_'));
  if (name.length + suffix.length > 64) name = '';
  return (name + suffix).replace(/^_/, '');
}

/**
 * rows:   { a, d, c, oonGroups: [...], posGroups: [...], hospital: [{cat, row}], b: {file: row}, area: [...], region: [...] }
 *         each row an object keyed by lowercased column name; b holds the plan's
 *         row of each file named in fhir/pbp-crosswalk.json
 * source: { year, downloaded, releaseLabel }
 * Returns { doc, errors, warnings }. When errors is non-empty, doc is null.
 * warnings: [{ kind, detail }], conditions that do not stop the import.
 */
function buildDocument(rows, source) {
  const errors = [];
  const warnings = [];
  const warn = (kind, detail) => warnings.push({ kind, detail });
  const { a, d } = rows;
  const key = { contract: a.pbp_a_hnumber, plan: a.pbp_a_plan_identifier, segment: pad3(a.segment_id) };
  const keyText = `${key.contract}-${key.plan}-${key.segment}`;
  const planType = a.pbp_a_plan_type;
  if (!MVP_PLAN_TYPES[planType]) {
    errors.push(`plan type ${planType} (${PLAN_TYPE_LABELS[planType] || 'not in the dictionary'}) is outside the importer's scope: ` +
      'HMO, HMOPOS, Local PPO and Regional PPO only (spec section 1)');
    return { doc: null, errors, warnings };
  }
  if (!d) errors.push('no pbp_Section_D.txt row');
  for (const col of ['pbp_a_plan_name', 'pbp_a_org_marketing_name']) if (!a[col] || !a[col].trim()) errors.push(`${col} is blank`);
  if (errors.length) return { doc: null, errors, warnings };

  const { accumulators, notes: accNotes } = buildAccumulators(d, rows.c, planType, errors);
  const network_tiers = buildTiers(rows.c, rows.oonGroups.length > 0, rows.posGroups.length > 0, rows.hospital, errors);
  const area = buildServiceArea(rows.area, rows.region, source.year, errors);
  if (errors.length) return { doc: null, errors, warnings };
  // An HMO with no out-of-network or point-of-service tier that still fills
  // Section D's out-of-network families keeps the file's wording; the note says
  // so (spec section 4.3). HMO-POS plans are decision 4 (buildAccumulators).
  const hasPos = network_tiers.some((t) => t.tier_id === 'POS');
  if (!network_tiers.some((t) => t.tier_id === 'OUT') && !hasPos) {
    const oonSlots = Object.keys(accumulators).filter((k) => k.startsWith('oon_'));
    const combMoop = q(d, 'pbp_d_comb_max_enr_amt_yn') === '1';
    if (oonSlots.length || combMoop) {
      accNotes.push(`The plan declares no out-of-network benefit (pbp_Section_C pbp_c_oon_yn "${rows.c ? rows.c.pbp_c_oon_yn : ''}") ` +
        `and no point-of-service option, yet Section D fills ${[...oonSlots, ...(combMoop ? ['the combined out-of-pocket maximum'] : [])].join(' and ')}. ` +
        'The values are written with the file\'s own network wording.');
    }
  }

  const ctx = {
    tiers: network_tiers,
    oonGroups: groupsFor(rows.oonGroups, 'OUT'),
    posGroups: groupsFor(rows.posGroups, 'POS'),
    ded: deductibleScopes(d, rows.c, planType, accumulators),
    moop: moopScopes(d, planType, accumulators),
    skipped: [],
  };
  const benefits = buildBenefits(rows, ctx, errors, warn);
  if (errors.length) return { doc: null, errors, warnings };

  const doc = {};
  doc.plan_id = planIdFor(a, keyText);
  doc.plan_identifiers = [
    { system: 'cms_contract_plan_segment', value: keyText },
    { system: 'cms_contract_id', value: key.contract },
    { system: 'cms_pbp_id', value: key.plan },
  ];
  doc.plan_name = a.pbp_a_plan_name.trim();
  doc.carrier = a.pbp_a_org_marketing_name.trim();
  doc.plan_type = MVP_PLAN_TYPES[planType];
  doc.plan_year = area.planYear;
  doc.market = 'medicare_advantage';
  if (area.service_area) doc.service_area = area.service_area;
  doc.network_tiers = network_tiers;
  doc.accumulators = accumulators;
  doc.benefits = benefits;

  const excerpts = [
    `CMS Plan Benefit Package (PBP) Benefits, contract year ${source.year}, release "${source.releaseLabel}" ` +
      `(${PBP_ZIP(source.year)}), downloaded ${source.downloaded}. Files read: ${READ_FILES.join(', ')}. ` +
      `PBP key: pbp_a_hnumber "${a.pbp_a_hnumber}", ` +
      `pbp_a_plan_identifier "${a.pbp_a_plan_identifier}", segment_id "${a.segment_id}" (written padded to 3 digits in plan_identifiers).`,
    `Plan type: pbp_a_plan_type "${planType}" (${PLAN_TYPE_LABELS[planType]}), written as plan_type "${MVP_PLAN_TYPES[planType]}".`,
    'Section A values with no Benefit Plan Standard field, verbatim: ' +
      SECTION_A_UNCARRIED.filter((col) => (a[col] || '') !== '').map((col) => cell(a, col)).join('; ') + '.',
    area.excerpt,
    ...accNotes,
    'Every non-blank Section D deductible and out-of-pocket cell, verbatim, in file order: ' + accumulatorCells(d).join('; ') + '.',
    `Benefits: the ${CROSSWALK.benefits.length} service categories in fhir/pbp-crosswalk.json (the workgroup MVP), ${benefits.length} written. ` +
      'Other PBP service categories are not imported yet (docs/specs/pbp-importer.md section 8).',
    ctx.skipped.length
      ? `Medicare-covered categories with no copay or coinsurance answer in the file, not written (${cell(a, 'pbp_a_ben_cov')}): ${ctx.skipped.join('; ')}.`
      : null,
  ];
  doc.source_references = excerpts.filter(Boolean).map((excerpt) => ({ excerpt }));
  doc.schema_version = SCHEMA_VERSION;
  return { doc, errors: [], warnings };
}

function serialize(doc) {
  return JSON.stringify(doc, null, 2) + '\n';
}

// The file name of a golden document, as the Marketplace importer builds it:
// carrier and plan name, text in parentheses dropped, cut back at "_" to 64
// characters, lowercased, "_" changed to "-". When 2 golden plans would share a
// slug, the contract-plan-segment key is appended to both.
function baseSlug(doc) {
  const part = (s) => idFromName(s.replace(/\([^)]*\)/g, ' '));
  let id = [part(doc.carrier), part(doc.plan_name)].filter(Boolean).join('_');
  while (id.length > 64) id = id.slice(0, id.lastIndexOf('_'));
  return id.toLowerCase().replace(/_/g, '-');
}

function docKey(doc) {
  return doc.plan_identifiers.find((p) => p.system === 'cms_contract_plan_segment').value;
}

function goldenSlugs(docs) {
  const bases = docs.map(baseSlug);
  return docs.map((doc, i) => (bases.filter((b) => b === bases[i]).length > 1 ? `${bases[i]}-${docKey(doc).toLowerCase()}` : bases[i]));
}

// ---- reading the files ------------------------------------------------------------------------
function pbpDir(dataDir, year) {
  const dir = path.join(dataDir, String(year));
  if (!fs.existsSync(dir)) throw new Error(`no folder ${path.relative(REPO_ROOT, dir)}; download the contract year ${year} files first (spec section 11)`);
  const names = fs.readdirSync(dir);
  const find = (name) => {
    const hits = names.filter((f) => f.toLowerCase() === name.toLowerCase());
    if (hits.length !== 1) throw new Error(`expected 1 file named ${name} (any case) in ${path.relative(REPO_ROOT, dir)}, found ${hits.length}`);
    return path.join(dir, hits[0]);
  };
  return { dir, find };
}

function readManifest(dir, override) {
  const manifest = path.join(dir, 'download.json');
  const m = fs.existsSync(manifest) ? JSON.parse(fs.readFileSync(manifest, 'utf8')) : {};
  const downloaded = override || m.downloaded;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(downloaded || '')) throw new Error(`no download date: pass --downloaded YYYY-MM-DD or add "downloaded" to ${path.relative(REPO_ROOT, manifest)}`);
  return { downloaded, releaseLabel: m.release_label || '(not recorded)' };
}

function parseKey(s) {
  const m = /^([A-Z]\d{4})-(\d{3})-(\d{3})$/.exec(s || '');
  if (!m) throw new Error(`--plan must be contract-plan-segment, for example H2406-013-000; got "${s}"`);
  return { contract: m[1], plan: m[2], segment: m[3] };
}

async function loadPlan({ dataDir = DATA_DIR, year, plan, downloaded }) {
  const key = parseKey(plan);
  const { dir, find } = pbpDir(dataDir, year);
  const one = async (file, required) => {
    const r = await rowsFor(find(file), key);
    if (r.length > 1) throw new Error(`${file}: ${r.length} rows for ${plan}`);
    if (required && r.length === 0) throw new Error(`no plan ${plan} in ${file}`);
    return r[0] || null;
  };
  const a = await one('pbp_Section_A.txt', true);
  const rows = {
    a,
    d: await one('pbp_Section_D.txt', false),
    c: await one('pbp_Section_C.txt', false),
    oonGroups: await rowsFor(find('pbp_Section_C_OON.txt'), key),
    posGroups: await rowsFor(find('pbp_Section_C_POS.txt'), key),
    hospital: [],
    b: {},
    area: await rowsFor(find('PlanArea.txt'), key),
    region: await rowsFor(find('PlanRegionArea.txt'), key),
  };
  for (const file of B_FILES) {
    const row = await one(file, false);
    if (row) rows.b[file] = row;
  }
  for (const cat of HOSPITAL_TIER_CATEGORIES) {
    if (rows.b[cat.file]) rows.hospital.push({ cat, row: rows.b[cat.file] });
  }
  return { rows, source: { year, ...readManifest(dir, downloaded) } };
}

// Returns { doc, warnings }; throws when the plan cannot be imported.
async function importPlan(opts) {
  const { rows, source } = await loadPlan(opts);
  const { doc, errors, warnings } = buildDocument(rows, source);
  if (errors.length) throw new Error(`${opts.plan} cannot be imported:\n  ${errors.join('\n  ')}`);
  return { doc, warnings };
}

async function listPlans({ dataDir = DATA_DIR, year, contract }) {
  const { find } = pbpDir(dataDir, year);
  const out = [];
  await streamTsv(find('pbp_Section_A.txt'), (f, idx) => {
    if (f[0] !== contract) return;
    const r = {};
    for (const [h, i] of idx) r[h] = f[i];
    out.push(r);
  });
  out.sort((x, y) => (x.pbp_a_plan_identifier + pad3(x.segment_id) < y.pbp_a_plan_identifier + pad3(y.segment_id) ? -1 : 1));
  return out;
}

// ---- golden files and fixtures (spec section 13) --------------------------------------------
// Copies the header and the golden plans' records of every file the importer
// reads, byte for byte (latin1 maps each byte to 1 character and back), into
// FIXTURE_DIR/<year>/ under the same file names, with a download.json that
// keeps the release label and download date of the full files.
async function cutFile(src, dst, keys) {
  const out = fs.openSync(dst, 'w');
  let carry = '';
  let first = true;
  let kept = 0;
  const take = (rec) => {
    if (first) { first = false; fs.writeSync(out, rec + '\r\n', null, 'latin1'); return; }
    const f = rec.split('\t', 3);
    if (!/^\d{1,3}$/.test(f[2] || '')) return;
    if (keys.has(`${f[0]}-${f[1]}-${pad3(f[2])}`)) { fs.writeSync(out, rec + '\r\n', null, 'latin1'); kept++; }
  };
  for await (const chunk of fs.createReadStream(src, { highWaterMark: 1 << 20 })) {
    const parts = (carry + chunk.toString('latin1')).split('\r\n');
    carry = parts.pop();
    for (const p of parts) take(p);
  }
  if (carry !== '') take(carry);
  fs.closeSync(out);
  return kept;
}

async function writeFixtures({ dataDir = DATA_DIR, fixtureDir = FIXTURE_DIR } = {}) {
  const lines = [];
  for (const year of [...new Set(GOLDEN.map((g) => g.year))]) {
    const keys = new Set(GOLDEN.filter((g) => g.year === year).map((g) => g.plan));
    const { dir, find } = pbpDir(dataDir, year);
    const outDir = path.join(fixtureDir, String(year));
    fs.mkdirSync(outDir, { recursive: true });
    const counts = {};
    for (const name of READ_FILES) {
      const src = find(name);
      counts[path.basename(src)] = await cutFile(src, path.join(outDir, path.basename(src)), keys);
    }
    const m = readManifest(dir);
    const manifest = {
      description: `Rows of the golden plans cut from the CMS PBP Benefits files, contract year ${year}, by node scripts/from-pbp.js --write-fixtures. ` +
        'Each file holds the original header line and the plans\' records, byte for byte. For scripts/from-pbp.test.js.',
      downloaded: m.downloaded,
      release_label: m.releaseLabel,
      source: PBP_ZIP(year),
      plans: [...keys],
      records: counts,
    };
    fs.writeFileSync(path.join(outDir, 'download.json'), JSON.stringify(manifest, null, 2) + '\n');
    lines.push(`wrote ${path.relative(REPO_ROOT, outDir)}: ${READ_FILES.length} files, ${Object.values(counts).reduce((a, b) => a + b, 0)} records`);
  }
  return lines;
}

// Builds the golden documents from dataDir (the full files by default) and
// returns [{ g, doc, file }] with each document's examples/ file name.
async function buildGolden({ dataDir = DATA_DIR } = {}) {
  const docs = [];
  for (const g of GOLDEN) {
    const { doc } = await importPlan({ dataDir, year: g.year, plan: g.plan });
    const errs = validateDocument(doc);
    if (errs.length) throw new Error(`${g.plan} output fails the v${SCHEMA_VERSION} schema:\n  ${errs.join('\n  ')}`);
    docs.push({ g, doc });
  }
  const slugs = goldenSlugs(docs.map((x) => x.doc));
  return docs.map((x, i) => ({ ...x, file: `${slugs[i]}.pbp.json` }));
}

// ---- schema check (local files, no network) ------------------------------------------------
function validateDocument(doc) {
  const Ajv2020 = require('ajv/dist/2020');
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  try { require('ajv-formats')(ajv); } catch (e) { /* optional */ }
  const schema = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'schema', 'v' + SCHEMA_VERSION, 'benefit-plan.schema.json'), 'utf8'));
  const validate = ajv.compile(schema);
  return validate(doc) ? [] : validate.errors.map((e) => `${e.instancePath || '(root)'} ${e.message}`);
}

// ---- CLI ----------------------------------------------------------------------------------------
async function main(argv) {
  const opt = {};
  for (let i = 0; i < argv.length; i++) {
    const x = argv[i];
    if (x === '--year') opt.year = Number(argv[++i]);
    else if (x === '--plan') opt.plan = argv[++i];
    else if (x === '--contract') opt.contract = argv[++i];
    else if (x === '--out' || x === '-o') opt.out = argv[++i];
    else if (x === '--data') opt.dataDir = path.resolve(argv[++i]);
    else if (x === '--downloaded') opt.downloaded = argv[++i];
    else if (x === '--write-golden') opt.writeGolden = true;
    else if (x === '--write-fixtures') opt.writeFixtures = true;
    else if (x === '-h' || x === '--help') {
      console.log('usage: node scripts/from-pbp.js --year <YYYY> --plan <H1234-567-000> [--out <file>]\n' +
        '       node scripts/from-pbp.js --year <YYYY> --contract <H1234>\n' +
        '       node scripts/from-pbp.js --write-golden      regenerate examples/*.pbp.json from the full files\n' +
        '       node scripts/from-pbp.js --write-fixtures    re-cut test/fixtures/pbp/ from the full files\n' +
        '       options: --data <dir> (default data/pbp), --downloaded <YYYY-MM-DD>');
      return 0;
    } else {
      console.error(`error: unknown argument "${x}"`);
      return 1;
    }
  }
  try {
    if (opt.writeGolden || opt.writeFixtures) {
      if (opt.writeFixtures) for (const line of await writeFixtures({ dataDir: opt.dataDir })) console.log(line);
      if (opt.writeGolden) {
        for (const { g, doc, file } of await buildGolden({ dataDir: opt.dataDir })) {
          fs.writeFileSync(path.join(EXAMPLES_DIR, file), serialize(doc));
          console.log(`wrote examples/${file}  (CY${g.year} ${g.plan})`);
        }
      }
      return 0;
    }
    if (!opt.year) throw new Error('--year is required');
    if (opt.contract) {
      if (!/^[A-Z]\d{4}$/.test(opt.contract)) throw new Error(`--contract must be like H2406; got "${opt.contract}"`);
      const rows = await listPlans(opt);
      if (rows.length === 0) { console.log(`no plans for contract ${opt.contract} in contract year ${opt.year}`); return 0; }
      for (const r of rows) {
        console.log([`${r.pbp_a_hnumber}-${r.pbp_a_plan_identifier}-${pad3(r.segment_id)}`,
          `${r.pbp_a_plan_type} ${PLAN_TYPE_LABELS[r.pbp_a_plan_type] || '?'}`,
          r.pbp_a_eghp_yn === '1' ? 'employer' : 'individual',
          r.pbp_a_special_need_flag === '1' ? 'SNP' : '-',
          r.pbp_a_plan_name, r.pbp_a_segment_name].join('\t'));
      }
      return 0;
    }
    if (!opt.plan) throw new Error('give --plan <contract-plan-segment>, or --contract <contract> to list plans');
    const { doc, warnings } = await importPlan(opt);
    const errs = validateDocument(doc);
    if (errs.length) throw new Error(`output fails the v${SCHEMA_VERSION} schema:\n  ${errs.join('\n  ')}`);
    for (const w of warnings) console.error(`warning: ${w.kind}: ${w.detail}`);
    const text = serialize(doc);
    if (opt.out) fs.writeFileSync(opt.out, text);
    else process.stdout.write(text);
    return 0;
  } catch (e) {
    console.error('error: ' + e.message);
    return 1;
  }
}

module.exports = {
  streamTsv, rowsFor, buildDocument, serialize, loadPlan, importPlan, listPlans, validateDocument, parseKey, pad3,
  HOSPITAL_TIER_CATEGORIES, MVP_PLAN_TYPES, B_FILES, READ_FILES, CROSSWALK, GOLDEN, baseSlug, goldenSlugs, buildGolden, writeFixtures,
  pbpDir, DATA_DIR, EXAMPLES_DIR, FIXTURE_DIR, SCHEMA_VERSION,
};

if (require.main === module) main(process.argv.slice(2)).then((code) => process.exit(code));
