#!/usr/bin/env node
/**
 * Copies the converter outputs and BPS FHIR definitions into a static-site folder
 * and writes an index.json listing every InsurancePlan file.
 *
 * Usage (from the repo root, with benefit-plan-docs checked out beside this repo):
 *   node scripts/publish-fhir.js ../benefit-plan-docs/static/fhir
 *
 * Layout written under the target folder:
 *   InsurancePlan/<id>.json          the golden Bundles from examples/fhir/, unchanged
 *   StructureDefinition/<name>.json  from fhir/definitions/
 *   CodeSystem/<name>.json           from fhir/definitions/
 *   index.json                       plain JSON list of the InsurancePlan files (not a FHIR resource)
 *
 * The files are static downloads, not a FHIR API. Output is deterministic.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { toInsurancePlanBundle, exampleFiles, EXAMPLES_DIR, GOLDEN_DIR } = require('./to-insuranceplan.js');

const REPO_ROOT = path.resolve(__dirname, '..');
const DEFS_DIR = path.join(REPO_ROOT, 'fhir', 'definitions');
const SITE = 'https://benefitplanstandard.org/fhir/';
const BPS_EXT = 'https://benefitplanstandard.org/fhir/StructureDefinition/';

const MA_LABEL = 'Medicare Advantage, read from the CMS Summary of Benefits, validates against the v1.2.0 draft only.';

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

function copyText(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.writeFileSync(to, fs.readFileSync(from, 'utf8').replace(/\r\n/g, '\n'));
}

function indexEntry(file) {
  const bps = readJson(path.join(EXAMPLES_DIR, file));
  const plan = toInsurancePlanBundle(bps).entry[0].resource;
  const golden = path.join(GOLDEN_DIR, plan.id + '.json');
  const published = readJson(golden).entry[0].resource;
  const placed = published.coverage.reduce((n, c) => n + c.benefit.length, 0);
  const unmapped = published.extension.filter((e) => e.url === BPS_EXT + 'bps-unmapped-benefit').length;
  const entry = {
    id: plan.id,
    plan_name: bps.plan_name,
    carrier: bps.carrier,
    plan_type: bps.plan_type,
    plan_year: bps.plan_year,
    bps_schema_version: bps.schema_version,
    bps_example: 'examples/' + file,
    path: 'InsurancePlan/' + plan.id + '.json',
    url: SITE + 'InsurancePlan/' + plan.id + '.json',
    benefits_placed: placed,
    benefits_unmapped: unmapped,
  };
  if (bps.market === 'medicare_advantage') entry.label = MA_LABEL;
  return entry;
}

function main(argv) {
  if (argv.length !== 1) {
    console.error('usage: node scripts/publish-fhir.js <target-folder>   e.g. ../benefit-plan-docs/static/fhir');
    return 1;
  }
  const target = path.resolve(argv[0]);
  const files = exampleFiles();
  const entries = files.map(indexEntry);

  for (const e of entries) {
    copyText(path.join(GOLDEN_DIR, e.id + '.json'), path.join(target, e.path));
    console.log('wrote ' + e.path);
  }
  for (const name of fs.readdirSync(DEFS_DIR).filter((f) => f.endsWith('.json')).sort()) {
    const [kind, ...rest] = name.split('-');
    const out = path.join(target, kind, rest.join('-'));
    copyText(path.join(DEFS_DIR, name), out);
    console.log('wrote ' + path.relative(target, out).replace(/\\/g, '/'));
  }

  const index = {
    description: 'Static FHIR R4 Bundles, one per Benefit Plan Standard example, each holding one InsurancePlan and the Organization it references. These are downloadable files, not a FHIR API or endpoint. Generated by scripts/to-insuranceplan.js in the benefit-plan-schema repository.',
    profile: 'http://hl7.org/fhir/us/insurance-card/StructureDefinition/sbc-insurance-plan',
    package: 'hl7.fhir.us.insurance-card#2.0.0-ballot',
    profile_status: 'draft, experimental; ballot-stage',
    fhir_version: '4.0.1',
    bps_repository: 'https://github.com/Benefit-Plan-Standard/benefit-plan-schema',
    converter_spec: 'https://github.com/Benefit-Plan-Standard/benefit-plan-schema/blob/main/docs/specs/insuranceplan-converter.md',
    plans: entries,
  };
  fs.writeFileSync(path.join(target, 'index.json'), JSON.stringify(index, null, 2) + '\n');
  console.log('wrote index.json (' + entries.length + ' plans)');
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));
